/* Reviews regression tests never contact production or create real orders/reviews. */
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'C:/Users/Mostafa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const mock=`
KenoFirebase.init=async()=>null;KenoFirebase.loadDesignSettings=async()=>null;KenoFirebase.fetchLiveCatalog=async()=>null;
KenoFirebase.getCurrentUser=()=>window.__user||null;KenoFirebase.checkAdminAuthorization=async()=>({authorized:true,role:'EDITOR'});KenoFirebase.onAuthStateChanged=async callback=>{window.__auth=callback;return()=>{}};
KenoFirebase.getOrders=async()=>[];KenoFirebase.listReviewSubmissions=async()=>[];
window.__reads=0;window.__writes=[];window.__failRead=true;
KenoFirebase.listReviews=async()=>{__reads++;if(__failRead)throw Object.assign(Error('permissions'),{code:'permission-denied'});return window.__reviews||[];};
KenoFirebase.submitReview=async review=>{if(window.__failSubmit)throw Object.assign(Error('permissions'),{code:'permission-denied'});__writes.push(review);if(window.__holdSubmit)await new Promise(r=>window.__finishSubmit=r);};
KenoFirebase.reviewInvite=async()=>({id:'KENO-TEST',reviewToken:'a'.repeat(48),serviceIds:['pubg','netflix'],status:'delivered'});
`;
(async()=>{const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{let body=fs.readFileSync(file);if(file.endsWith(path.join('js','firebase.js')))body=Buffer.from(body+mock);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.woff':'font/woff'})[path.extname(file)]||'application/octet-stream');res.end(body);}catch(_){res.writeHead(404);res.end();}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),url='http://127.0.0.1:'+server.address().port;await ctx.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000);await page.goto(url);await page.locator('#reviewRetry').waitFor();assert(await page.locator('#reviewSubmit').isDisabled());assert(await page.locator('#reviewService').isDisabled());assert(await page.locator('#reviewNoOrders').isVisible());
await page.evaluate(()=>__failRead=false);await page.locator('#reviewRetry').click();await page.waitForFunction(()=>document.querySelector('.review-empty h3')?.textContent.includes('أول تجربة'));assert(await page.locator('#reviewSummary').isHidden());
await page.locator('.review-link-entry summary').click();await page.locator('#reviewLinkInput').fill('bad-link');await page.locator('#reviewApplyLink').click();assert.match(await page.locator('#reviewStatus').textContent(),/مش صحيح/);assert.equal(await page.locator('#reviewClaim').inputValue(),'');
const link=url+'/#review/KENO-TEST/'+'a'.repeat(48)+'/pubg,netflix';await page.locator('#reviewLinkInput').fill(link);await page.locator('#reviewApplyLink').click();assert.equal(await page.locator('#reviewClaim').inputValue(),'KENO-TEST');assert.deepEqual(await page.locator('#reviewService option').evaluateAll(es=>es.map(e=>e.value)),['','pubg','netflix']);await page.locator('#reviewService').selectOption('pubg');await page.locator('#reviewStars [data-rating="2"]').click();assert.equal(await page.locator('#reviewRating').inputValue(),'2');assert.equal(await page.locator('#reviewStars .filled').count(),2);await page.locator('#reviewName').fill('عميل تجريبي');await page.locator('#reviewComment').fill('تجربة اختبار داخل البيئة المحلية فقط');
await page.evaluate(()=>{__failSubmit=true;KenoReviews.render(getStoreCatalog());});assert.equal(await page.locator('#reviewService').inputValue(),'pubg');assert.equal(await page.locator('#reviewRating').inputValue(),'2');await page.locator('#reviewSubmit').click();await page.waitForFunction(()=>document.getElementById('reviewStatus').dataset.kind==='error');assert.match(await page.locator('#reviewComment').inputValue(),/تجربة اختبار/);assert.equal(await page.evaluate(()=>__writes.length),0);
await page.evaluate(()=>{__failSubmit=false;__holdSubmit=true;});await page.locator('#reviewSubmit').click();await page.waitForFunction(()=>window.__finishSubmit);assert(await page.locator('#reviewSubmit').isDisabled());assert(await page.locator('#reviewClaim').isDisabled());assert(await page.locator('#reviewService').isDisabled());assert(await page.locator('#reviewApplyLink').isDisabled());await page.locator('#reviewForm').evaluate(e=>e.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(await page.evaluate(()=>__writes.length),1);await page.evaluate(()=>{__holdSubmit=false;__finishSubmit();});await page.waitForFunction(()=>document.getElementById('reviewStatus').dataset.kind==='success');assert.equal(await page.locator('#reviewService option[value=pubg]').count(),0);assert.equal(await page.locator('#reviewService').inputValue(),'netflix');assert.equal(await page.locator('#reviewComment').inputValue(),'');assert.equal(await page.evaluate(()=>__writes[0].rating),2);
await page.evaluate(async()=>{window.__reviews=Array.from({length:7},(_,i)=>({id:'r'+i,serviceId:i===6?'netflix':'pubg',name:i===0?'<img onerror=alert(1)>':'عميل '+i,comment:'تجربة شراء '+i,rating:i===0?1:4,timestamp:1780000000000+i*86400000}));__reviews.push({rating:5,name:'invalid',comment:'ignore',timestamp:null});await KenoReviews.loadReviews(true);});assert.equal(await page.locator('#testimonialsGrid article').count(),6);assert.equal(await page.locator('#reviewPublishedCount').textContent(),'٧ تقييم منشور');await page.locator('#reviewLoadMore').click();assert.equal(await page.locator('#testimonialsGrid article').count(),7);assert.equal(await page.locator('#testimonialsGrid img').count(),0);assert.equal(await page.locator('.verified-tag').count(),0);assert.equal(await page.locator('#testimonialsGrid time').first().getAttribute('datetime'),new Date(1780000000000+6*86400000).toISOString());await page.locator('#reviewFilter').selectOption('netflix');assert.equal(await page.locator('#testimonialsGrid article').count(),1);await page.locator('#reviewFilter').selectOption('');
for(const width of [320,390,1440])for(const theme of ['dark','light']){await page.setViewportSize({width,height:1000});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(400);await page.locator('#testimonials').screenshot({path:path.join(root,'qa','reviews-'+width+'-'+theme+'.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}
await page.evaluate(async()=>{window.__user={email:'editor@example.test'};await __auth(__user);KenoOrder.copyToClipboard=async text=>window.__copied=text;location.hash='#admin';});await page.locator('[data-admin-tab=adminOrders]').click();await page.locator('#reviewInviteOrder').fill('KENO-TEST');await page.locator('#reviewInvite').click();await page.waitForFunction(()=>window.__copied);assert.match(await page.evaluate(()=>__copied),/\/pubg,netflix$/);assert.deepEqual(errors,[]);console.log('PASS: error/retry/empty states; claim/service binding; stars; preserved drafts; duplicate prevention; low ratings, exact dates, escaping/filter/pagination; admin links; 320/390/1440 dark/light');await ctx.close();}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
