/* Expand the explicit source cascade into one deployable stylesheet. No dependencies. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'assets', 'store.bundle.css');
function read(file) {
  let css = fs.readFileSync(file, 'utf8');
  css = css.replace(/url\((["']?)([^)'"\s]+)\1\)/g, (all, quote, value) => {
    if (/^(?:data:|https?:|\/\/|#)/.test(value)) return all;
    const target = path.resolve(path.dirname(file), value);
    return 'url("' + path.relative(path.dirname(output), target).replaceAll('\\', '/') + '")';
  });
  css = css.replace(/@import\s+url\("([^"]+)"\);/g, (_, value) => read(path.resolve(path.dirname(output), value)));
  return css.replace(/\/\*[\s\S]*?\*\//g, '').split(/\r?\n/).map(line=>line.trim()).filter(Boolean).join('\n');
}
fs.writeFileSync(output, '/* Generated by node tools/build-styles.cjs; edit style.css and its imports. */\n' + read(path.join(root, 'style.css')) + '\n');
console.log('CSS bundle:', fs.statSync(output).size, 'bytes');
